#!/bin/sh

sudo dnf install --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y

sudo dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm

sudo dnf install vim-powerline -y

echo "if [ -f `which powerline-daemon` ]; then
        powerline-daemon -q
        POWERLINE_BASH_CONTINUATION=1
        POWERLINE_BASH_SELECT=1
        . /usr/share/powerline/bash/powerline.sh
      fi" >> ~/.bashrc

echo 'python3 from powerline.vim import setup as powerline_setup
      python3 powerline_setup()
      python3 del powerline_setup
      set laststatus=2 " Always display the statusline in all windows
      set showtabline=2 " Always display the tabline, even if there is only one tab
      set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
      set t_Co=256
      ' >> ~/.vimrc
